config/routes.rb
Rails.application.routes.draw do

  devise_for :users, 
    path: 'acesso', 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'sair', 
      password: 'recuperar', 
      confirmation: 'confirme', 
      unlock: 'desbloquear',
      registration: 'cadastro', 
      sign_up: 'participar' 
    }, controllers: { 
      omniauth_callbacks: 'users/omniauth_callbacks' 
    }

  get '/politica-de-privacidade', to: 'frontend#privacy'
  get '/sitemaps', to: 'sitemaps#index'
  get '/painel', to: 'questions#index', as: :painel
  get '/painel/surpresa', to: 'questions#randomic', as: :random
  resources :topics, only: [:index, :show], path: 'temas'
  scope(only: [:index, :new, :create, :show], path_names: { new: 'fabrica' }) do
    resources :questions, path: 'vote' do
      get :results, to: :results, as: :results, on: :member, path: 'resultados'
      match :vote, to: :vote, on: :member, via: [:post, :patch]
    end
  end

  devise_for :admins, path: 'admin'
  namespace :admin do
    resources :topics, only: [:index, :create, :update]
    resources :questions do
      patch :approve, to: :approve, on: :member
      patch :reject, to: :reject, on: :member
    end
    root to: 'dashboard#index'
  end

  resources :profiles, only: [:update]
  get '/perfil/:token/editar', to: 'profiles#edit', as: :account_edit
  get '/perfil(/:token)', to: 'profiles#index', as: :account

  root to: 'frontend#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include PublicActivity::Common
  include Sluggable

  STATUSES = {
    awaiting_moderation: 'Aguardando Aprovação',
    approved: 'Aprovada',
    approved_published: 'Aprovada e Publicada',
    rejected: 'Pergunta Rejeitada'
  }

  REJECTION_REASONS = {
    repeated: 'Pergunta Repetida',
    no_politics: 'Pergunta foge ao tema político',
    irrelevant: 'Considerada Irrevelante'
  }
  
  belongs_to :topic, counter_cache: true
  belongs_to :user
  has_many :options, dependent: :delete_all
  has_many :votes

  validates :title, presence: true

  store_accessor :meta, :views
  store_accessor :meta, :image_url

  after_create :setup!

  scope :active, -> { where(published: true) }
  scope :await, -> { where(status: :awaiting_moderation) }
  scope :spotlight, -> { active.where(featured: true) }
  scope :anonymo, -> { active.where(anonymous: true) }

  def views
    self.meta['views'] || 0
  end

  def image_url
    self.meta['image_url']
  end

  def increment_view!
    self.meta = {} unless self.meta
    views = self.meta['views']
    self.meta['views'] = views ? views.to_i + 1 : 1
    self.save
  end

  def log_activities activity_key
    self.create_activity key: activity_key, owner: self.user if activity_key
  end

  def rejected?
    self.status == 'rejected'
  end

  protected

    def setup!
      create_yes_no_options # Create Options
      # Log Activities
      log_activities(self.anonymous ? "question.submit_anonymous" : "question.submit_public")
      # Setup Metadata
      self.update_column(:meta, { views: 0, image_url: nil })
    end

    # Its prepared to multiple choices
    def create_yes_no_options
      if self.options.empty? && self.kinda == 'yes_no'
        ['Sim', 'Não'].map { |choice| self.options.create(name: choice) }
      end
    end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::AdminController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :approve, :reject]

  # GET /questions
  def index
    @questions = Question.all
  end

  # GET /questions/1
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to admin_question_path(@question), notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /questions/1
  def update
    @question.title = question_params[:title]
    old_title = @question.changed_attributes[:title] if @question.changed_attributes.include?(:title)
    if @question.update(question_params)
      @question.create_activity(key: 'question.title_updated', owner: current_admin, parameters: { title: old_title }) if old_title
      @question.create_activity key: 'question.updated', owner: current_admin
      redirect_to admin_question_path(@question), notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    redirect_to admin_questions_url, notice: 'Question was successfully destroyed.'
  end

  def approve
    @question.update({ published: true, accepted: true, status: 'approved_published', topic_id: question_params[:topic_id] })
    @question.log_activities("question.approved_published")
    redirect_to :back, notice: 'Aprovada e Publicada!'
  end

  def reject
    @question.update({ published: false, accepted: false, status: 'rejected', rejection_reason: question_params[:rejection_reason] })
    @question.log_activities("question.rejected")
    redirect_to :back, warn: 'Rejeitada!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.by_slug(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def question_params
      params.require(:question).permit(:title, :published, :closed, :user_id, :topic_id, :anonymous, :accepted, :rejection_reason)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create, :vote]
  before_action :retrieve, only: [:show, :results, :vote]

  def index
    @questions = current_user.questions.all
    redirect_to new_question_path if @questions.empty?
  end

  def new
    @question = Question.new
  end

  def show
    @question.increment_view!
    @vote = current_user ? current_user.votes.find_or_initialize_by(question_id: @question.id) : Vote.new
  end

  def create
    @question = Question.find_by(title: question_params['title'])
    if @question
      redirect_to :back, alert: 'Opa, parece que alguém já fez esta pergunta. Que tal outra?'
    else
      @question = current_user.questions.new(question_params)
      if @question.save(validate: false)
        redirect_to questions_path, notice: 'Sua pergunta foi enviada e está aguardando moderação.'
      else
        redirect_to :back, error: 'Ops'
      end
    end
  end

  def randomic
    # TODO: exclude asked questions
    question = Question.active.order('RANDOM()').first
    redirect_to question_path(question)
  end

  def vote
    @vote = current_user.votes.find_or_create_by(question_id: @question.id)
    option = @question.options.find(params[:vote][:option])
    if option
      @vote.option_id = option.id
      @vote.anonymous = params[:vote][:anonymous]
      @vote.save
    end
    redirect_to random_path
  end

  private

    # Only allow a trusted parameter "white list" through.
    def question_params
      params.require(:question).permit(:title, :anonymous)
    end

    def retrieve
      @question = Question.by_slug(params[:id])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_card.html.erb
<div class="col-xl-3 col-lg-4 col-md-4 col-sm-6 col-xs-12 <%= 'rejected' if question.rejected? %>">
  <div class="question-card">
    <div class="bubble">
      <div class="middle">
        <h1><%= question.title %></h1>
        <%= Question::STATUSES[question.status.to_sym] %>
        <% if question.rejected? %>
          <br /><i class="fa fa-info"> Motivo: <%= Question::REJECTION_REASONS[question.rejection_reason.try(:to_sym)] %></i>
        <% end %>
        <% if question.published? %>
          <br /><%= link_to 'Responder', question_path(question), class: 'btn btn-skin' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <div class="form-group">
    <%= f.text_area :title, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <div class="checkbox">
      <label><%= f.check_box :anonymous %> Tornar pergunta anônima?</label>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit 'Enviar Sugestão de Pergunta', class: 'btn btn-huge btn-default' %>
  </div>
<% end %>

app/views/questions/index.html.erb
  <%= link_to 'Sugira uma Pergunta', new_question_path, class: 'btn btn-lg btn-success pull-right' %>
<div class="area">

  <div class="row">
    <% @questions.each do |question| %>
      <%= render 'card', question: question  %>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<div class="area col-md-6 col-md-offset-3 text-center">
  <h2>Contribua com o nosso acervo de perguntas. Você sugere e a gente aprova. Vamos lá! <strong>Qual grande questão política você gostaria de saber da opinião pública?</strong> </h2>
  <div class="col-lg-12">
    <%= render 'form', question: @question %>
  </div>
</div>

app/views/questions/show.html.erb
<%
  seo [
    { property: 'description', content: "#{@question.title} em #{@question.topic.name}" },
    { property: 'og:title', content: @question.title, type: 'property' },
    { property: 'og:image', content: @question.image_url || 'oclima-politico.png', type: 'property' },
    { property: 'og:description', content: "A gente quer saber: #{@question.title} - Dê sua opinião.", type: 'property' }
  ]
  title @question.title
%>

  <section class="big-question">
    <div class="container-fluid">
      <div class="caption">
        <div class="inner">
        <%= form_for([@question, @vote], url: vote_question_path(@question), html: { class: 'ac-checkbox ac-checkmark' }) do |f| %>
          <h1><%= @question.title %></h1>
          <div class="text-center">
            <ul class="ac-custom">
            <%= f.collection_radio_buttons :option, @question.options, :id, :name do |o| %>
              <li>
                <%= o.radio_button checked: @vote.option && (@vote.option.id == o.object.id) %>
                <%= o.label(class: 'ac') %>
              </li>
            <% end %>
            </ul>

            <label><%= f.check_box :anonymous, checked: @vote.anonymous? %> Voto Anônimo</label>
            <br />
            <%= f.submit 'Confirmar', class: 'btn btn-info btn-lg btn-confirm' %>
            <br />

            <%= link_to results_question_path(@question), class: 'btn btn-inverted', data: { toggle: "modal", target: ".results" } do %>
              <i class="fa fa-bar-chart"></i> Ver Resultados
            <% end %>

            <%= link_to random_path, title: 'Pular esta pergunta e responder a outra.', class: 'btn btn-inverted', 'data-turbolinks' => 'true' do %>
              Pular Esta Pergunta <i class="fa fa-caret-right"></i>
            <% end %>
          </div>
          <% end %>

          <span class="metadata">
            ID #<%= @question.id %>
            | <i class="fa fa-eye"></i> <%= @question.views %>
            | <a data-toggle="modal" data-target=".history"><i class="fa fa-clock-o"></i> Histórico</a>
             | <div class="fb-share-button" data-href="<%= url(request.path) %>" data-layout="button_count"></div>
          </span>
        </div>
      </div>
      
    </div>
  </section>

<div class="modal fade history" tabindex="-1" role="dialog" aria-labelledby="historyLog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title up" id="historyLog"><b>Histórico</b></h3>
      </div>
        <div class="modal-body">
        <% @question.activities.each do |activity| %>
          <p>
            <i class="fa fa-clock"></i> <%= activity.created_at.strftime('%d/%m/%Y %H:%M') %>:
          <% if activity.key == 'question.updated' %>
            <%= t(activity.key, admin_name: activity.owner.try(:name)) %>
          <% elsif activity.key == 'question.submit_public' %>
            <%= t(activity.key, user_name: link_to(activity.owner.try(:name) || activity.owner.email, account_path(activity.owner.profile.token))).html_safe %>
          <% elsif activity.key == 'question.title_updated' %>
            <%= t(activity.key) %> <i><%= activity.parameters %></i>
          <% else %>
            <%= t(activity.key) %>
          <% end %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade results" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body text-center">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4>Os resultados ainda estão sendo computados, <br /> mas temos aqui uma parcial.</h4>
        <div id="donutchart"></div>
        <p>Em breve você poderá consultar o resultado final. ;)</p><br />
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  document.addEventListener("turbolinks:render", function(){
    checkbxsCheckmark = Array.prototype.slice.call(document.querySelectorAll('form.ac-checkmark input[type="radio"]'));

    checkbxsCheckmark.forEach(function(el, i){ 
      if(el.checked){
        var svg = createSVGEl();
        el.parentNode.appendChild(svg);
        draw(el, 'checkmark'); 
      }
    });
  });
</script>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  google.charts.load("current", {packages:["corechart"]});
  google.charts.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Question', 'Votes per Option'],
      <% @question.options.each do |option| %>
        ['<%= option.name %>', <%= option.votes.size %>],
      <% end %>
    ]);

    var options = {
      title: '<%= @question.title %>',
      pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
    chart.draw(data, options);
  }
</script>