config/routes.rb
Rails.application.routes.draw do

  devise_for :users, 
    path: 'acesso', 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'sair', 
      password: 'recuperar', 
      confirmation: 'confirme', 
      unlock: 'desbloquear',
      registration: 'cadastro', 
      sign_up: 'participar' 
    }, controllers: { 
      omniauth_callbacks: 'users/omniauth_callbacks' 
    }

  get '/politica-de-privacidade', to: 'frontend#privacy'
  get '/sitemaps', to: 'sitemaps#index'
  get '/painel', to: 'questions#index', as: :painel
  get '/painel/surpresa', to: 'questions#randomic', as: :random
  resources :topics, only: [:index, :show], path: 'temas'
  scope(only: [:index, :new, :create, :show], path_names: { new: 'fabrica' }) do
    resources :questions, path: 'vote' do
      get :results, to: :results, as: :results, on: :member, path: 'resultados'
      match :vote, to: :vote, on: :member, via: [:post, :patch]
    end
  end

  devise_for :admins, path: 'admin'
  namespace :admin do
    resources :topics, only: [:index, :create, :update]
    resources :questions do
      patch :approve, to: :approve, on: :member
      patch :reject, to: :reject, on: :member
    end
    root to: 'dashboard#index'
  end

  resources :profiles, only: [:update]
  get '/perfil/:token/editar', to: 'profiles#edit', as: :account_edit
  get '/perfil(/:token)', to: 'profiles#index', as: :account

  root to: 'frontend#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/views/shared/_about.html.erb
<section id="sobre" class="inner-section color-dark bg-white">
  <div class="container marginbot-50">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="section-heading text-center">
          <h2>O Clima Político</h2>
          <div class="divider-header"></div>
        </div>

        <div class="text-center">
          <p>O Clima Político tenta medir a temperatura do cenário político no âmbito nacional, convidando todos os brasileiros a opiniar sobre questões atuais diversas. <strong>Não somos ligados a nenhum partido político nem estamos aqui para promover qualquer político, personalidade pública, servidor público ou empresa.</strong></p>

          <p>Os resultados aqui apresentados são computados em tempo real, com votos alimentados pelos usuários e não representa nossa opinião. No entanto, esperamos estas questões aqui introduzidas possam gerar uma reflexão maior sobre os assuntos em cada brasileiro e que a opinião pública possa ser levada em consideração pelos nossos governantes.</p>

          <p>Você também pode contribuir submentendo perguntas para descobrir a opinião pública sobre determinado assunto. Clique <%= link_to 'aqui', new_user_session_path %> para começar a enviar e responder.</p>
        </div>
      </div>
    </div>    
  </div>

</section>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <%= link_to image_tag('oclima.png', width: 100), root_path %>
      </div>
      <div class="col-md-7">
        <ul class="footer-menu">
          <li><a>Termos de Uso (Em Breve)</a></li>
          <li>
            <div class="fb-like" data-share="true" data-width="450" data-show-faces="true"></div>
          </li>
        </ul>
      </div>
      <div class="col-md-3 text-right">
        <p>&copy;Copyright 2016  <a target="_blank" href="http://wipcodes.com/"> <%= image_tag('wipcodes.png', width: '100') %></a></p>
      </div>
    </div>  
  </div>
</footer>

app/views/shared/_nav.html.erb
<div id="navigation">
  <nav class="navbar navbar-custom" role="navigation">
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <div class="site-logo">
            <a href="/" class="brand"></a>
          </div>
        </div>
        <div class="col-md-10">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
              <i class="fa fa-bars"></i>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="menu">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Início', root_path %></li>
              <li><%= link_to 'Temas', topics_path %></li>
              <li><%= link_to 'Pergunta Aleatória', random_path %></li>
              <% if user_signed_in? %>
                <li><%= link_to 'Fábrica de Perguntas', questions_path %></li>
                <li><%= link_to 'Perfil', account_path(current_user.profile.token) %></li>
                <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to 'Participe!', new_user_session_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div><!-- /.container -->
  </nav>
</div> 

app/views/shared/_questions.html.erb
<% @topics.each do |topic| %>
  <div class="col-xs-6 col-sm-4 col-md-4 topic">
    <div class="card">
      <div class="middle">
        <h5><%= link_to topic.name, topic_path(topic) %></h5>
        <div class="divider"></div>
        <!-- TODO: retrieve this questions by ajax -->
        <p><%= topic.questions.active.last.try(:title) %></p>
        <%= link_to 'explore outras questões', topic_path(topic), class: 'btn btn-inverted' %>
      </div>
    </div>
  </div>
<% end %>