config/routes.rb
Rails.application.routes.draw do

  devise_for :users, 
    path: 'acesso', 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'sair', 
      password: 'recuperar', 
      confirmation: 'confirme', 
      unlock: 'desbloquear',
      registration: 'cadastro', 
      sign_up: 'participar' 
    }, controllers: { 
      omniauth_callbacks: 'users/omniauth_callbacks' 
    }

  get '/politica-de-privacidade', to: 'frontend#privacy'
  get '/sitemaps', to: 'sitemaps#index'
  get '/painel', to: 'questions#index', as: :painel
  get '/painel/surpresa', to: 'questions#randomic', as: :random
  resources :topics, only: [:index, :show], path: 'temas'
  scope(only: [:index, :new, :create, :show], path_names: { new: 'fabrica' }) do
    resources :questions, path: 'vote' do
      get :results, to: :results, as: :results, on: :member, path: 'resultados'
      match :vote, to: :vote, on: :member, via: [:post, :patch]
    end
  end

  devise_for :admins, path: 'admin'
  namespace :admin do
    resources :topics, only: [:index, :create, :update]
    resources :questions do
      patch :approve, to: :approve, on: :member
      patch :reject, to: :reject, on: :member
    end
    root to: 'dashboard#index'
  end

  resources :profiles, only: [:update]
  get '/perfil/:token/editar', to: 'profiles#edit', as: :account_edit
  get '/perfil(/:token)', to: 'profiles#index', as: :account

  root to: 'frontend#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include PublicActivity::Common
  include Sluggable

  STATUSES = {
    awaiting_moderation: 'Aguardando Aprovação',
    approved: 'Aprovada',
    approved_published: 'Aprovada e Publicada',
    rejected: 'Pergunta Rejeitada'
  }

  REJECTION_REASONS = {
    repeated: 'Pergunta Repetida',
    no_politics: 'Pergunta foge ao tema político',
    irrelevant: 'Considerada Irrevelante'
  }
  
  belongs_to :topic, counter_cache: true
  belongs_to :user
  has_many :options, dependent: :delete_all
  has_many :votes

  validates :title, presence: true

  store_accessor :meta, :views
  store_accessor :meta, :image_url

  after_create :setup!

  scope :active, -> { where(published: true) }
  scope :await, -> { where(status: :awaiting_moderation) }
  scope :spotlight, -> { active.where(featured: true) }
  scope :anonymo, -> { active.where(anonymous: true) }

  def views
    self.meta['views'] || 0
  end

  def image_url
    self.meta['image_url']
  end

  def increment_view!
    self.meta = {} unless self.meta
    views = self.meta['views']
    self.meta['views'] = views ? views.to_i + 1 : 1
    self.save
  end

  def log_activities activity_key
    self.create_activity key: activity_key, owner: self.user if activity_key
  end

  def rejected?
    self.status == 'rejected'
  end

  protected

    def setup!
      create_yes_no_options # Create Options
      # Log Activities
      log_activities(self.anonymous ? "question.submit_anonymous" : "question.submit_public")
      # Setup Metadata
      self.update_column(:meta, { views: 0, image_url: nil })
    end

    # Its prepared to multiple choices
    def create_yes_no_options
      if self.options.empty? && self.kinda == 'yes_no'
        ['Sim', 'Não'].map { |choice| self.options.create(name: choice) }
      end
    end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::AdminController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :approve, :reject]

  # GET /questions
  def index
    @questions = Question.all
  end

  # GET /questions/1
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to admin_question_path(@question), notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /questions/1
  def update
    @question.title = question_params[:title]
    old_title = @question.changed_attributes[:title] if @question.changed_attributes.include?(:title)
    if @question.update(question_params)
      @question.create_activity(key: 'question.title_updated', owner: current_admin, parameters: { title: old_title }) if old_title
      @question.create_activity key: 'question.updated', owner: current_admin
      redirect_to admin_question_path(@question), notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    redirect_to admin_questions_url, notice: 'Question was successfully destroyed.'
  end

  def approve
    @question.update({ published: true, accepted: true, status: 'approved_published', topic_id: question_params[:topic_id] })
    @question.log_activities("question.approved_published")
    redirect_to :back, notice: 'Aprovada e Publicada!'
  end

  def reject
    @question.update({ published: false, accepted: false, status: 'rejected', rejection_reason: question_params[:rejection_reason] })
    @question.log_activities("question.rejected")
    redirect_to :back, warn: 'Rejeitada!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.by_slug(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def question_params
      params.require(:question).permit(:title, :published, :closed, :user_id, :topic_id, :anonymous, :accepted, :rejection_reason)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create, :vote]
  before_action :retrieve, only: [:show, :results, :vote]

  def index
    @questions = current_user.questions.all
    redirect_to new_question_path if @questions.empty?
  end

  def new
    @question = Question.new
  end

  def show
    @question.increment_view!
    @vote = current_user ? current_user.votes.find_or_initialize_by(question_id: @question.id) : Vote.new
  end

  def create
    @question = Question.find_by(title: question_params['title'])
    if @question
      redirect_to :back, alert: 'Opa, parece que alguém já fez esta pergunta. Que tal outra?'
    else
      @question = current_user.questions.new(question_params)
      if @question.save(validate: false)
        redirect_to questions_path, notice: 'Sua pergunta foi enviada e está aguardando moderação.'
      else
        redirect_to :back, error: 'Ops'
      end
    end
  end

  def randomic
    # TODO: exclude asked questions
    question = Question.active.order('RANDOM()').first
    redirect_to question_path(question)
  end

  def vote
    @vote = current_user.votes.find_or_create_by(question_id: @question.id)
    option = @question.options.find(params[:vote][:option])
    if option
      @vote.option_id = option.id
      @vote.anonymous = params[:vote][:anonymous]
      @vote.save
    end
    redirect_to random_path
  end

  private

    # Only allow a trusted parameter "white list" through.
    def question_params
      params.require(:question).permit(:title, :anonymous)
    end

    def retrieve
      @question = Question.by_slug(params[:id])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admin/questions/_form.html.erb
<%= form_for([:admin,question], html: { class: 'form-horizontal', role: 'form' }) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :topic_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.select :topic_id, Topic.all.collect{|t|[t.name, t.id]}, { include_blank: true }, class: 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_field :title, class: 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :user_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_field :user_id, class: 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :status, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.select :status, [], class: 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :rejection_reason, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.select :rejection_reason, [], class: 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :kinda, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.select :kinda, ['yes_no'], class: 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :slug, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_field :slug, class: 'form-control', disabled: true %></div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Publicado?</label>
    <div class="col-sm-10">
      <div class="checkbox">
        <label><%= f.check_box :published %> Sim</label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Anonimo?</label>
    <div class="col-sm-10">
      <div class="checkbox">
        <label><%= f.check_box :anonymous %> Sim</label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Destaque?</label>
    <div class="col-sm-10">
      <div class="checkbox">
        <label><%= f.check_box :featured %> Sim</label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Aceito?</label>
    <div class="col-sm-10">
      <div class="checkbox">
        <label><%= f.check_box :accepted %> Sim</label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit 'Enviar', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/admin/questions/edit.html.erb
<div class="panel mb25">
  <div class="panel-heading border">
    Atualizar Pergunta
  </div>
  <div class="panel-body">
    <div class="row no-margin">
      <div class="col-lg-12">
        <%= render 'form', question: @question %>
        <%= link_to 'Show', admin_question_path(@question) %> |
        <%= link_to 'Back', admin_questions_path %>
      </div>
    </div>
  </div>
</div>

app/views/admin/questions/index.html.erb
<div class="panel mb25">
  <div class="panel-heading border">Perguntas <%= link_to 'Nova Pergunta', new_admin_question_path, class: 'btn btn-default pull-right' %></div>

  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-bordered table-striped mb0">
        <thead>
          <tr>
            <th>Título</th>
            <th>Topico</th>
            <th>Publicado?</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @questions.each do |question| %>
            <tr>
              <td><%= question.title %></td>
              <td><%= question.topic.try(:name) %></td>
              <td><%= question.published? ? 'Sim' : 'Não' %></td>
              <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, admin_question_path(question) %></td>
              <td><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_question_path(question) %></td>
              <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, admin_question_path(question), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/questions/new.html.erb
<div class="panel mb25">
  <div class="panel-heading border">
    Nova Pergunta
  </div>
  <div class="panel-body">
    <div class="row no-margin">
      <div class="col-lg-12">
        <%= render 'form', question: @question %>
        <%= link_to 'Back', admin_questions_path %>
      </div>
    </div>
  </div>
</div>

app/views/admin/questions/show.html.erb
<div class="col-sm-8">
  <div class="panel panel-primary">
    <div class="panel-heading"><%= @question.title %></div>
    <div class="panel-body">
      <p><b>Tema:</b> <%= @question.topic.try(:name) %></p>

      <p>
        <strong>Title:</strong>
        <%= @question.title %>
      </p>

      <p>
        <strong>Situação:</strong>
        <%= Question::STATUSES[@question.status.to_sym] %>
      </p>

      <p>
        <strong>Published:</strong>
        <%= @question.published %>
      </p>

      <p>
        <strong>Closed:</strong>
        <%= @question.closed %>
      </p>

      <p>
        <strong>Aceita:</strong>
        <%= @question.accepted %>
      </p>

      <p>
        <strong>Motivo de Rejeição:</strong>
        <%= Question::REJECTION_REASONS[@question.rejection_reason.try(:to_sym)] %>
      </p>



      <p>
        <strong>Destaque:</strong>
        <%= @question.featured %>
      </p>

      <p>
        <strong>Anonimo:</strong>
        <%= @question.anonymous %>
      </p>

      <p>
        <strong>Meta:</strong>
        <%= @question.meta %>
      </p>

      <p>
        <strong>User:</strong>
        #<%= @question.user.try(:id) %>
        <%= @question.user.try(:email) %>
      </p>

      <div class="pull-right">
        <%= link_to 'Editar', edit_admin_question_path(@question), class: 'btn btn-primary' %>
        <%= link_to 'voltar', admin_questions_path, class: 'btn btn-default' %>
      </div>

    </div>
  </div>
</div>

<div class="col-sm-4">
  <div class="panel">
    <div class="panel-heading border">
      Moderar Pergunta
    </div>
    <div class="panel-body">

      <%= form_for([:admin, @question], url: approve_admin_question_path(@question), html: { role: 'form' }) do |f| %>
        <div class="form-group">
          <%= f.label :topic_id, 'Tema: ', class: 'col-sm-2 control-label' %>
          <div class="col-sm-10"><%= f.select :topic_id, Topic.all.collect{|t|[t.name, t.id]}, { include_blank: true }, { class: 'form-control', required: true } %></div>
        </div>

        <br />
        <br />

        <div class="form-group pull-right">
          <%= f.submit 'Aprovar e Publicar', class: 'btn btn-success' %>
        </div>
      <% end %>

      <br />
      <br />
      <hr />
      <br />
      <br />

      <%= form_for([:admin, @question], url: reject_admin_question_path(@question), html: { role: 'form' }) do |f| %>
        <div class="form-group">
          <%= f.label :rejection_reason, 'Motivo: ', class: 'col-sm-2 control-label' %>
          <div class="col-sm-10"><%= f.select :rejection_reason, Question::REJECTION_REASONS.collect{|t|[t[1], t[0]]}, { include_blank: true }, { class: 'form-control', required: true } %></div>
        </div>

        <br />
        <br />

        <div class="form-group pull-right">
          <%= f.submit 'Rejeitar Pergunta', class: 'btn btn-danger' %>
        </div>
      <% end %>


    </div>
  </div>

  <br />

  <div class="panel">
    <div class="panel-heading border">
      Opções
    </div>
    <div class="panel-body">
      <ul>
        <% @question.options.each do |option| %>
          <li>
            <%= option.name %> (<%= option.votes_count %>)
          </li>
        <% end %>
      </ul>
    </div>
  </div>

</div>

<div class="col-sm-8">
  <div class="panel">
    <div class="panel-heading border">Histórico</div>
    <div class="panel-body">
      <% @question.activities.each do |activity| %>
        <p>
          <i class="fa fa-clock-o"></i> <%= t(activity.created_at) %>:
        <% if activity.key == 'question.updated' %>
          <%= t(activity.key, admin_name: activity.owner.try(:name)) %>
        <% elsif activity.key == 'question.title_updated' %>
          <%= t(activity.key) %> <i><%= activity.parameters %></i>
        <% elsif activity.key == 'question.submit_public' %>
          <%= t(activity.key, user_name: activity.owner.try(:name) || "##{activity.owner.id}") %>
        <% else %>
          <%= t(activity.key) %>
        <% end %>
        </p>
      <% end %>
    </div>
  </div>
</div>