config/routes.rb
Rails.application.routes.draw do

  devise_for :users, 
    path: 'acesso', 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'sair', 
      password: 'recuperar', 
      confirmation: 'confirme', 
      unlock: 'desbloquear',
      registration: 'cadastro', 
      sign_up: 'participar' 
    }, controllers: { 
      omniauth_callbacks: 'users/omniauth_callbacks' 
    }

  get '/politica-de-privacidade', to: 'frontend#privacy'
  get '/sitemaps', to: 'sitemaps#index'
  get '/painel', to: 'questions#index', as: :painel
  get '/painel/surpresa', to: 'questions#randomic', as: :random
  resources :topics, only: [:index, :show], path: 'temas'
  scope(only: [:index, :new, :create, :show], path_names: { new: 'fabrica' }) do
    resources :questions, path: 'vote' do
      get :results, to: :results, as: :results, on: :member, path: 'resultados'
      match :vote, to: :vote, on: :member, via: [:post, :patch]
    end
  end

  devise_for :admins, path: 'admin'
  namespace :admin do
    resources :topics, only: [:index, :create, :update]
    resources :questions do
      patch :approve, to: :approve, on: :member
      patch :reject, to: :reject, on: :member
    end
    root to: 'dashboard#index'
  end

  resources :profiles, only: [:update]
  get '/perfil/:token/editar', to: 'profiles#edit', as: :account_edit
  get '/perfil(/:token)', to: 'profiles#index', as: :account

  root to: 'frontend#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/views/admin/shared/_launch.html.erb
 <!-- quick launch panel -->
  <div class="quick-launch-panel">
    <div class="container">
      <div class="quick-launcher-inner">
        <a href="javascript:;" class="close" data-toggle="quick-launch-panel">×</a>
        <div class="css-table-xs">
          <div class="col">
            <a href="app-calendar.html">
              <i class="icon-marquee"></i>
              <span>Calendar</span>
            </a>
          </div>
          <div class="col">
            <a href="app-gallery.html">
              <i class="icon-drop"></i>
              <span>Gallery</span>
            </a>
          </div>
          <div class="col">
            <a href="app-messages.html">
              <i class="icon-mail"></i>
              <span>Messages</span>
            </a>
          </div>
          <div class="col">
            <a href="app-social.html">
              <i class="icon-speech-bubble"></i>
              <span>Social</span>
            </a>
          </div>
          <div class="col">
            <a href="charts-flot.html">
              <i class="icon-pie-graph"></i>
              <span>Analytics</span>
            </a>
          </div>
          <div class="col">
            <a href="javascript:;">
              <i class="icon-esc"></i>
              <span>Documentation</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /quick launch panel -->

app/views/admin/shared/_sidebar.html.erb
<!-- sidebar panel -->
  <div class="sidebar-panel offscreen-left">

    <div class="brand">

      <!-- logo -->
      <div class="brand-logo">
        <!-- <img src="images/logo.png" height="15" alt=""> -->
      </div>
      <!-- /logo -->

      <!-- toggle small sidebar menu -->
      <a href="javascript:;" class="toggle-sidebar hidden-xs hamburger-icon v3" data-toggle="layout-small-menu">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </a>
      <!-- /toggle small sidebar menu -->

    </div>

    <!-- main navigation -->
    <nav role="navigation">

      <ul class="nav">

        <li>
          <a href='/admin'>
            <i class="fa fa-flask"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <li>
          <%= link_to admin_questions_path do %>
            <i class="fa fa-question-circle"></i>
            <span>Questões</span>
          <% end %>
        </li>
         <li>
          <%= link_to admin_topics_path do %>
            <i class="fa fa-plane"></i>
            <span>Temas</span>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_admin_session_path, method: :delete do %>
            <i class="fa fa-power-off"></i>
            <span>Sair</span>
          <% end %>
        </li>

      </ul>
    </nav>
    <!-- /main navigation -->

  </div>
  <!-- /sidebar panel -->

app/views/admin/shared/_top.html.erb
<!-- top header -->
<header class="header navbar">

  <div class="brand visible-xs">
    <!-- toggle offscreen menu -->
    <div class="toggle-offscreen">
      <a href="#" class="hamburger-icon visible-xs" data-toggle="offscreen" data-move="ltr">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>
    <!-- /toggle offscreen menu -->

    <!-- logo -->
    <div class="brand-logo">
      <%= image_tag 'admin/logo-dark.png', height: 15 %>
    </div>
    <!-- /logo -->

    <!-- toggle chat sidebar small screen-->
    <div class="toggle-chat">
      <a href="javascript:;" class="hamburger-icon v2 visible-xs" data-toggle="layout-chat-open">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>
    <!-- /toggle chat sidebar small screen-->
  </div>

  <ul class="nav navbar-nav navbar-right hidden-xs">
    <li>
      <a href="javascript:;" data-toggle="quick-launch-panel">
        <i class="fa fa-circle-thin"></i>
      </a>
    </li>

    <li>
      <a href="javascript:;" data-toggle="dropdown">
        <i class="fa fa-bell-o"></i>
        <div class="status bg-danger border-danger animated bounce"></div>
      </a>
      <ul class="dropdown-menu notifications">
        <li class="notifications-header">
          <p class="text-muted small">You have 3 new messages</p>
        </li>
        <li>
          <ul class="notifications-list">
            <li>
              <a href="javascript:;">
                <span class="pull-left mt2 mr15">
                  <%= image_tag 'admin/avatar.jpg', class: 'avatar avatar-xs img-circle' %>
                </span>
                <div class="overflow-hidden">
                  <span>Sean launched a new application</span>
                  <span class="time">2 seconds ago</span>
                </div>
              </a>
            </li>
            <li>
              <a href="javascript:;">
                <div class="pull-left mt2 mr15">
                  <div class="circle-icon bg-danger">
                    <i class="fa fa-chain-broken"></i>
                  </div>
                </div>
                <div class="overflow-hidden">
                  <span>Removed chrome from app list</span>
                  <span class="time">4 Hours ago</span>
                </div>
              </a>
            </li>
            <li>
              <a href="javascript:;">
                <span class="pull-left mt2 mr15">
                  <%= image_tag 'admin/face3.jpg', class: 'avatar avatar-xs img-circle' %>
                </span>
                <div class="overflow-hidden">
                  <span class="text-muted">Jack Hunt has registered</span>
                  <span class="time">9 hours ago</span>
                </div>
              </a>
            </li>
          </ul>
        </li>
        <li class="notifications-footer">
          <a href="javascript:;">See all messages</a>
        </li>
      </ul>
    </li>

    <li>
      <a href="javascript:;" data-toggle="dropdown">
        <%= image_tag 'admin/avatar.jpg', class: 'header-avatar img-circle ml10' %>
        <span class="pull-left"><%= current_admin.name %></span>
      </a>
      <ul class="dropdown-menu">
        <li>
          <a href="javascript:;">Settings</a>
        </li>
        <li>
          <a href="javascript:;">Upgrade</a>
        </li>
        <li>
          <a href="javascript:;">
            <span class="label bg-danger pull-right">34</span>
            <span>Notifications</span>
          </a>
        </li>
        <li>
          <a href="javascript:;">Help</a>
        </li>
        <li><%= link_to 'Sair', destroy_admin_session_path, method: :delete %></li>
      </ul>

    </li>

    <li>
      <a href="javascript:;" class="hamburger-icon v2" data-toggle="layout-chat-open">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </li>
  </ul>
</header>
<!-- /top header -->